### PR TITLE
More infomation when missing secret or token

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by popomore** [comment]
Coverage 100%

```
Statements   : 100% ( 46/46 )
Branches     : 100% ( 40/40 )
Functions    : 100% ( 9/9 )
Lines        : 100% ( 41/41 )
```

**Comment by popomore** [comment]
@jonathanong

**Comment by popomore** [comment]
@jonathanong Any idea?

**Comment by jonathanong** [comment]
looks good

**Comment by jonathanong** [comment]
looks good just added you as a collab + npm

**Comment by popomore** [comment]
+1 and Thx

**Comment by popomore** [comment]
+ koa-csrf@2.4.0

**Pull request merged**
